import mongoose from "mongoose";

const UserSchema = new mongoose.Schema({
  id: Number,
  donor_firstname: String,
  donor_lastname: String,
  donor_city: String,
  donor_state: String,
  donor_zip: String,
  donor_is_eligible_for_express_lane: Boolean,
  donor_phone: String,
  created_at: Date,
  order_number: String,
  contribution_form: String,
  refcodes: {},
  refcode: String,
  recurring_period: String,
  recurring_duration: String,
  is_paypal: Boolean,
  is_mobile: Boolean,
  is_express: Boolean,
  with_express_lane: Boolean,
  express_signup: Boolean,
  unique_identifier: String,
  status: String,
  text_message_option: String,
  custom_fields: [],
  sequence: Number,
  entity_id: Number,
  committee_name: String,
  amount: Number,
  paid_at: String,
  lineitem_id: Number,
  form_name: String,
  form_managing_entity_name: String,
  form_managing_entity_committee_name: String,
});

const User = mongoose.model("User", UserSchema);
export default User;
